// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAE6liob2UxhdzSFJDVKRg1gmN209HLk',
    appId: '1:658979738135:web:dfde33296338da83ca8252',
    messagingSenderId: '658979738135',
    projectId: 'blog-eb3ee',
    authDomain: 'blog-eb3ee.firebaseapp.com',
    storageBucket: 'blog-eb3ee.appspot.com',
    measurementId: 'G-WSY3W1W0XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDar07i1olsd7vOMBIpKo2tyST6rfd35Z0',
    appId: '1:658979738135:android:d54524a24526e39dca8252',
    messagingSenderId: '658979738135',
    projectId: 'blog-eb3ee',
    storageBucket: 'blog-eb3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-2qRwmf_6NJJ8qP2xBZUoBHOBEbYgSs',
    appId: '1:658979738135:ios:2784f25b16ad5638ca8252',
    messagingSenderId: '658979738135',
    projectId: 'blog-eb3ee',
    storageBucket: 'blog-eb3ee.appspot.com',
    iosBundleId: 'com.KC.blog',
  );
}
